### ISSUE TITLE
Tree item labels enhancement

### ISSUE THREAD

**Issue by jarvistesting** [vscode-elements/elements#108]
How can I add checkbox to tree item labels and other menu action?
How to add click action on item click

**Comment by bendera** [comment]
Hi,

Currently, you can't add a checkbox to the tree item.

Actions can be added in this way:
https://bendera.github.io/vscode-webview-elements/components/vscode-tree/#actions

An item dispatches a `vsc-select` event when it's clicked. See:
https://bendera.github.io/vscode-webview-elements/components/vscode-tree/#basic-example
