### ISSUE TITLE
Deselect tree

### ISSUE THREAD

**Issue by qarlosalberto** [vscode-elements/elements#132]
Is it possible to unselect a tree item?

**Comment by qarlosalberto** [comment]
My idea is to deselect all when the user click outside the tree.

**Comment by bendera** [comment]
Currently, only can be resolved by a workaround. Let's take this example and let's assume the selected item is the "vscode-tree.test.ts":
https://vscode-elements.github.io/components/tree/#custom-icons

```javascript
const tree = document.querySelector('#custom-icons-example');
tree.data[0].subItems[2].selected = false;
tree.requestUpdate();
```

You have to find the selected element in the tree data somehow. The payload of the `vsc-tree-select` event contains the selected menu item data, and every menu item has a `path` property. In the above example the path is `0/2`.

**Comment by bendera** [comment]
I found that the Tree component has a private `_getItemByPath` method. I can expose that and/or add a `deselectAll` public method.

**Comment by qarlosalberto** [comment]
that would be great!!

**Comment by bendera** [comment]
New version has been released.

**Comment by qarlosalberto** [comment]
thank you very much!
