### ISSUE TITLE
Tree item description

### ISSUE THREAD

**Issue by qarlosalberto** [vscode-elements/elements#136]
Is it possible to add an item description as VSCode tree?

(you can see the description in grey)

![imagen](https://github.com/vscode-elements/elements/assets/5955143/f81df625-5129-4696-bb3b-186e73164eb9)

**Comment by qarlosalberto** [comment]
with the library:

![imagen](https://github.com/vscode-elements/elements/assets/5955143/a02a7d56-08a7-4e2e-8c13-3a69c63c878f)

**Comment by bendera** [comment]
Yes, the description property exists in the TreeItem. It's slightly smaller and its opacity is 0.95. 

```javascript
document.querySelector('vscode-tree').getItemByPath([0,2]).description = "asfasf";
```

![image](https://github.com/vscode-elements/elements/assets/3748508/5e56ed99-2397-4dc1-9ed5-fe474e732070)

**Comment by qarlosalberto** [comment]
Could you use a similar color to native VSCode tree? It can be a little confusing:

![imagen](https://github.com/vscode-elements/elements/assets/5955143/52af0261-1be7-49ee-ae04-ac075277f9aa)

**Comment by bendera** [comment]
> Could you use a similar color to native VSCode tree?

I borrowed the styles of the timeline panel but neither the VSCode design is not consistent. I will add [css part](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) declarations to it, and you can customize it as you want.

**Comment by qarlosalberto** [comment]
that's great

**Comment by bendera** [comment]
Done.
