### ISSUE TITLE
Tree item tooltip

### ISSUE THREAD

**Issue by qarlosalberto** [vscode-elements/elements#137]
Is it possible to add a tooltip in the tree item? Similar to:

![imagen](https://github.com/vscode-elements/elements/assets/5955143/555eff66-7629-4cf5-81d3-4a4bf7a4d6dc)

**Comment by rijesha** [comment]
This would be a great feature to have. I have a long string for a file path. It would be nice if a user could hover over it and see the full string.
(As an aside, great project thanks for the work you have put into it)

**Comment by bendera** [comment]
I could add the ability to display a native tooltip. Only a native one, like the second screenshot, not a rich-text like in the first screenshot.

**Comment by rijesha** [comment]
A native one would be great

**Comment by bendera** [comment]
Done.

**Comment by rijesha** [comment]
Thanks!
