### ISSUE TITLE
Single-select combobox expand on focus

### ISSUE THREAD

**Issue by tradiff** [vscode-elements/elements#143]
This might be a feature request, but if you disagree, I can try to implement a javascript bandaid on my end.

When using a single-select in combobox mode, currently the list expands if the user clicks the arrow, or if the user clicks the textbox and starts typing.

Is there any way to expand the dropdown immediately upon the textbox receiving focus?

Basically let the user click the component, and then once they see the list, decide if they're going to click an item, or start typing to narrow the options.

**Comment by bendera** [comment]
I agree, it would be more comfortable if the dropdown opened automatically. I'll implement that.

**Comment by bendera** [comment]
Done.

**Comment by tradiff** [comment]
Works great! thanks!
