### ISSUE TITLE
Scrollable to bottom

### ISSUE THREAD

**Issue by qarlosalberto** [vscode-elements/elements#146]
How can I move a Scrollable element to the max bottom?

**Comment by bendera** [comment]
The component has a scrollMax property:
https://vscode-elements.github.io/components/scrollable/api/#Properties_scrollMax
You can combine it with the scrollPos:

```
const sc = document.querySelector('#my-scrollable');
sc.scrollPos = sc.scrollMax;
```

**Comment by qarlosalberto** [comment]
great! thank you very much
