### ISSUE TITLE
`npm i` reports many vulnerabilities

### ISSUE THREAD

**Issue by gjsjohnmurray** [vscode-elements/elements#166]
After I forked this repo, cloned locally and ran `npm i` I got a lot of messages and this summary:
```
45 vulnerabilities (2 low, 6 moderate, 32 high, 5 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

**Comment by bendera** [comment]
I've never seen this screen like this before.
![image](https://github.com/user-attachments/assets/129f87b1-24ec-4931-96aa-a4f5e539cb6f)
