### ISSUE TITLE
Icons colors wash out in the lighter themes

### ISSUE THREAD

**Issue by mikeburgh** [vscode-elements/elements#172]
Using some of the light themes (all but Solarized Light and Light Visual Studio ) the icon colors wash out against the background.

Here is a video showing it:

https://github.com/user-attachments/assets/946a9ba8-cbf3-41ea-b185-5aa3c43fa2cf

**Comment by mikeburgh** [comment]
Sorry, was looking into the fix for a PR and found some wayward css on my end.. Cleaned up and sorted!

**Comment by bendera** [comment]
Great! Where does this cool datagrid component come from?

**Comment by mikeburgh** [comment]
It's AG Grid: https://www.ag-grid.com/

The extension we are building with it and vscode-elements is for database management  (https://dbcode.io). I have not finished the page yet, but any modules we use we are giving lifetime subscriptions to any contributors/maintainers of them.. and yours is fantastic! , so if you uses databases and want a sub, let me know and I will get you a code.

**Comment by bendera** [comment]
>if you uses databases and want a sub, let me know and I will get you a code

Yes, please, I would be honored.

Its UI is so beautiful. It doesn't look like a website, but like an integral part of VSCode.

**Comment by mikeburgh** [comment]
It would be my pleasure.. If you can install the extension and sign in via the Accounts view once you click the DBCode icon in the activity bar I can then assign the subscription to you! 

That's the aim.. make it feel just like VSCode, but have all the features of the traditional DB tools.

**Comment by bendera** [comment]
Signed in with my github account.

Thank you!

**Comment by mikeburgh** [comment]
Thanks, applied!
