### ISSUE TITLE
Question: How to make icon inside button animated?

### ISSUE THREAD

**Issue by neko-para** [vscode-elements/elements#177]
E.g. setting `spin` property for the `vscode-icon` inside.

**Comment by bendera** [comment]
Ooops... That's a good question. I'll come up with a solution soon.

**Comment by bendera** [comment]
I added some properties/attributes to control the icon animation parameters: `icon-spin`, `icon-spin-duration`, `icon-after-spin`, `icon-after-spin-duration` 
Or you can place an animated icon within the button.

```html
<vscode-button>
  <vscode-icon spin spin-duration="1" name="sync" aria-hidden="true"></vscode-icon>
  Loading
</vscode-button>
```

**Comment by neko-para** [comment]
> I added some properties/attributes to control the icon animation parameters: `icon-spin`, `icon-spin-duration`, `icon-after-spin`, `icon-after-spin-duration` Or you can place an animated icon within the button.
> 
> ```
> <vscode-button>
>   <vscode-icon spin spin-duration="1" name="sync" aria-hidden="true"></vscode-icon>
>   Loading
> </vscode-button>
> ```

Actually I've tried adding icon directly inside button before, but the icon isn't properly aligned with text. The new `icon-spin` attribute works.

**Comment by bendera** [comment]
It wasn't aligned properly, but I also fixed the CSS.
