### ISSUE TITLE
SingleSelect: when inside a collapsible, popup options are truncated

### ISSUE THREAD

**Issue by neko-para** [vscode-elements/elements#178]
![QQ_1728394456930](https://github.com/user-attachments/assets/d8f881a4-5b3d-4b84-9288-bfcdf06b958d)

**Comment by bendera** [comment]
This is a complex issue and there isn't any simple solution to fix it. I added two options to the components that will help you fix this issue.

- The select got a `position` property, which controls the position of the dropdown. The valid values are "above" and "below".
- The overflow of body of the collapsible component is hidden by default, and for good reason. I defined a CSS part that you can use to modify this property. 

```css
vscode-collapsible::part(body) {
  overflow: visible;
}
```

With this CSS, the dropdown won't be truncated, but the bottom margin of the last element will push down the next element after the Collapsible component. Therefore it's your responsibility to fix this.

![Screenshot 2024-10-08 230940](https://github.com/user-attachments/assets/802b9f64-fad5-4baf-a291-a7a81eaaa86d)

I published a pre release version, please let me know if this solve your issue. You can install with: `npm i @vscode-elements/elements@next`

**Comment by neko-para** [comment]
![QQ_1728443633206](https://github.com/user-attachments/assets/5c83a265-2a84-4c1c-a6db-38a0a07ec023)

Seems that with the css everything works fine, and no extra margin appears. Maybe it's because there's an extra div between collapsible and single-select?

```html
            <vscode-collapsible title="abc" open>
                <div id="indexPanel">
                    <vscode-single-select>
                        <vscode-option>abc</vscode-option>
                        <vscode-option selected>def</vscode-option>
                    </vscode-single-select>
                </div>
            </vscode-collapsible>
```

```css
#indexPanel {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;

    padding: 0.5rem;
}
```

**Comment by bendera** [comment]
Only the children with margins are affected. In my example, the last line is a `<p>` tag with default vertical margins.
