### ISSUE TITLE
RadioGroup: multiple groups mistakenly influence others

### ISSUE THREAD

**Issue by neko-para** [vscode-elements/elements#179]
I'm using jquery to dynamic create contents, thus here's the screenshot of elements page

![QQ_1728394991827](https://github.com/user-attachments/assets/780b747c-8cfd-4cbf-9b0c-d4f0db7f83fd)

```typescript
        for (const opt of target.option) {
            const optId = `target-${target.id}-${opt.id}`;

            formEl.append($('<vscode-label></vscode-label>').text(opt.name).attr('for', optId));

            const selEl = $('<vscode-radio-group></vscode-radio-group>');
            selEl.attr('id', optId);

            for (const cs of opt.case) {
                const optEl = $('<vscode-radio></vscode-radio>');
                optEl.text(cs.name);
                if ((target.config[opt.id] ?? opt.def) === cs.value) {
                    optEl.attr('checked', '');
                }
                selEl.append(optEl);
            }
            formEl.append(selEl);
        }
```

![QQ_1728395027553](https://github.com/user-attachments/assets/18fc9221-5820-4198-801e-a4b4f5ca1ec2)

When I click one radio, other three all got unchecked.

https://github.com/user-attachments/assets/d310ff95-a032-4d00-8c38-62fb1add1595

**Comment by bendera** [comment]
Use different name attributes for the Debug/Release and the SAAS/Local groups.
