### ISSUE TITLE
TextField: pattern is not checked after value is changed by JavaScript

### ISSUE THREAD

**Issue by isc-bsaviano** [vscode-elements/elements#182]
Consider the following element:
```html
<vscode-textfield id="path" name="path" placeholder="/path" pattern="^(/.*)?$"></vscode-textfield>
```
When my Webview is restored after being hidden, I want to assign `path.value` to whatever the user had typed before the Webview was hidden. When I change the value, the `pattern` validation is not being re-run. According to the example [on this page](https://stackoverflow.com/questions/53226031/html-input-validity-not-checked-when-value-is-changed-by-javascript), it should be.

**Comment by bendera** [comment]
Thanks for the report, I'll investigate it.

**Comment by isc-bsaviano** [comment]
Thanks @bendera!

**Comment by bendera** [comment]
Fixed in the latest pre-release. Please check if it works.

`npm i @vscode-elements/elements@next`

**Comment by bendera** [comment]
`invalid` is only a styling property intended for custom validation. When true, the component turns red, and that's its entire purpose. If you want to use native form validation (which is what's happening in your case), the component will automatically turn red and get the `:invalid` pseudo-class. In this case, you should use the `checkValidity()` function to check if the text field is valid.

I should update the documentation to make this clearer.

**Comment by isc-bsaviano** [comment]
Thanks for clarifying, `checkValidity()` works! Should I create a new issue for the dropdown behavior, or just follow #178?

**Comment by bendera** [comment]
Create a new one, thanks. But before that try this:

**Comment by bendera** [comment]
Could you link your repo or make a reproducible example?

**Comment by isc-bsaviano** [comment]
For reference, here's a simple version of my HTML. The select options are added programmatically by JS on page load.

```html
        <form id="form">
            <vscode-tabs id="panels" selected-index="0" aria-label="Method & Path, Headers, Query Parameters and Body">
            <vscode-tab-header id="methodPathTab">METHOD & PATH</vscode-tab-header>
            <vscode-tab-panel id="methodPathView">
              <section class="component-container">
                <section class="path-grid">
                  <section class="path-grid-container">
                    <vscode-single-select id="webApp" name="webApp" position="below"></vscode-single-select>
                  </section>
                  <section class="path-grid-container">
                    <vscode-textfield id="path" name="path" placeholder="/path" pattern="^/.*$" required></vscode-textfield>
                  </section>
                </section>
              </section>
            </vscode-tab-panel>
          </vscode-tabs>
        </form>
        <vscode-divider></vscode-divider>
```

The sections are necessary because there are other elements that I've removed to simplify this example. The SingleSelect and TextField are rendered next to each other:

<img width="1006" alt="Screenshot 2024-10-10 at 11 48 12 AM" src="https://github.com/user-attachments/assets/17b74b28-3543-4c91-b991-0b53bd5ed285">

**Comment by bendera** [comment]
AH, okay. You are right, it seems it's the same situation as #178

**Comment by isc-bsaviano** [comment]
Thanks for confirming. I'll close this as fixed and follow #178. `1.6.3-pre-1` didn't fix it for me.

**Comment by bendera** [comment]
The good news is that it can be fixed without changing the Tabs component. Just overwrite the default styles of the TabPanel component:
```css
vscode-tab-panel {
  overflow: visible;
}
```

**Comment by isc-bsaviano** [comment]
That works perfectly with `1.6.3-pre.1`! Thank you so much for your help!
