### ISSUE TITLE
Types for `vsc-change` event

### ISSUE THREAD

**Issue by christian-bromann** [vscode-elements/elements#19]
Thanks for offering this great package!

It would be nice if the library could expose types for the `vsc-change` event based on given element. Let me know if this makes sense and I could look into adding it.

**Comment by bendera** [comment]
Thank you for your feedback!

That's a great idea. Honestly, I don't know how could I implement this, so I would appreciate your help.

**Comment by bendera** [comment]
I've rewritten the event handling part. Most of the components use native events if possible. When a component has a custom event, the event name is unique as contains the component name. Every custom event is exported as TypeScript type. When a component is imported its events will be registered as global events, so will be offered in the IDE autocomplete.
