### ISSUE TITLE
'VscodeLabel' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by brodao2** [vscode-elements/elements#197]
I'm trying to use VscodeLabel in a react component and I get the error:

```console
'VscodeLabel' cannot be used as a JSX component.
```

Any suggestions?

Grateful.

```typeScript
export class TdsLabel extends React.Component<TdsLabel> {
    render() {
        return (
            <React.Fragment>
                <VscodeLabel >
                    
                </VscodeLabel >
            </React.Fragment>
        );
    }
}
```

**Comment by bendera** [comment]
I haven't tried it yet, but at first glance, I see a whitespace in the VscodeLabel tag.

**Comment by bendera** [comment]
Ok, I've found it. I'll fix it right away.

**Comment by bendera** [comment]
Done. Please reinstall it with `npm i @vscode-elements/react-elements@latest`
