### ISSUE TITLE
React wrapper elements don't trigger change event

### ISSUE THREAD

**Issue by neko-para** [vscode-elements/elements#203]
Currently, neither of `VscodeSingleSelect` nor `VscodeRadio` call `onChange`. Manually addEventListener do help according to [comment](https://github.com/vscode-elements/elements/issues/184#issuecomment-2404752856), but as that issue has been closed and the react wrapper released, doesn't it solved? Or possibly because change event is kind of native events and have some special logic? But `VscodeButton` does trigger click event.

**Comment by neko-para** [comment]
addEventListener example, which works.

```typescript
const selEl = useRef<VscodeSingleSelectType | null>(null)

useEffect(() => {
    if (selEl.current) {
        const ls = (e: Event) => {
            console.log(e)
        }
        selEl.current.addEventListener('change', ls)

        return () => {
            selEl.current?.removeEventListener('change', ls)
        }
    }
}, [])

///

<VscodeSingleSelect
    ref={selEl}
>
```

onChange example, which doesn't work.

```typescript
function onChangeTarget(event: FormEvent<VscodeSingleSelectType>) {
}

///

<VscodeSingleSelect
    onChange={onChangeTarget}
>
```

**Comment by bendera** [comment]
Fixed https://github.com/vscode-elements/react-elements/releases/tag/v0.5.0
