### ISSUE TITLE
How can I let TabPanel use all space that Tabs provides?

### ISSUE THREAD

**Issue by neko-para** [vscode-elements/elements#208]
I can use css to make `vscode-tabs` to fulfill the screen, but the inner `vscode-tab-panel` still got the size that just contains its content. I've put a canvas inside it and using ResizeObserver to dynamic changing its size, thus I cannot just make the content bigger. I've tried adding `height: 100%` on `vscode-tab-panel`, but this makes it too tall (just the same height as the `vscode-tabs`)

`vscode-tabs` size
![QQ_1729590492289](https://github.com/user-attachments/assets/cf57d87b-80c1-42b3-b87b-417bdb88615d)

`vscode-tab-panel` size
![QQ_1729590506069](https://github.com/user-attachments/assets/ecbd21ba-449a-4201-b9e6-a2eb8fa98fc1)

`vscode-tab-panel` size with `height: 100%`
![QQ_1729590656210](https://github.com/user-attachments/assets/69671189-b7a4-4ec5-a462-0fb1d023672f)

**Comment by neko-para** [comment]
I've achieved it via overriding the layout `vscode-tabs` (e.g. by adding `display: flex` to it), but this does depend on the implementation, which shouldn't be the correct path.

**Comment by bendera** [comment]
I think the `<body>` has a 10px padding.

**Comment by neko-para** [comment]
> I think the `<body>` or the parent div has a 10px padding.

Yes, body do have a padding, thus it makes it not suitable to use `100%`, maybe.

**Comment by bendera** [comment]
I take this as resolved.

**Comment by neko-para** [comment]
> I take this as resolved.

Actually I don't think my approach is elegant. It relies on the implementation after all. It would be better to have a more official and robust way.
