### ISSUE TITLE
Using Webpack: BREAKING CHANGE: The request './components/VscodeTree' failed to resolve ...

### ISSUE THREAD

**Issue by brodao2** [vscode-elements/elements#213]
Sirs,

I migrated from @vscode-webtookit to @vscode-element.
In a development environment, my extension works without problems with @vscode-element, but for distribution I use WebPack.

When running webPack, I get the message below:

```
ERROR in ./node_modules/@vscode-elements/react-elements/dist/main.js 33:0-49
Module not found: Error: Can't resolve './components/VscodeTree' in 'W:\ws_tds_vscode\tds-webtoolkit\node_modules\@vscode-elements\react-elements\dist'       
Did you mean 'VscodeTree.js'?

BREAKING CHANGE: The request './components/VscodeTree' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.

Add the extension to the request.

```

Any suggestions on how to resolve it?

Grateful

**Comment by bendera** [comment]
Could you provide a reproducible example? If your extension includes a standalone frontend build that can be launched with minimal setup, that would be ideal.

**Comment by bendera** [comment]
Anyway, try this:

```
npm i @vscode-elements/react-elements@next
```

Please let me know if it resolved your issue, and I will publish it in the latest channel too.

**Comment by brodao2** [comment]
@bendera 

The initial incident has been resolved. Now, WebPack runs without problems. When running my application, the new error now occurs. 

```
Uncaught Error: Cannot find module './components/VscodeBadge'
    at webpackMissingModule (index.js:9439:42)
    at ./node_modules/@vscode-elements/react-elements/dist/main.js (index.js:9439:149)
    at __nested_webpack_require_458394__ (index.js:9530:1)
    at ./src/components/form/content.tsx (index.js:7730:26)
    at __nested_webpack_require_458394__ (index.js:9530:1)
    at ./src/components/form/form.tsx (index.js:7911:35)
    at __nested_webpack_require_458394__ (index.js:9530:1)
    at index.js:9623:14
    at index.js:9679:2
    at ../../tds-webtoolkit/dist/index.js (index.js:9681:11)
```

Thank you for your attention.

**Comment by brodao2** [comment]
@bendera 

I made the suggested adjustments, but the problem persists.

The project in which this occurrence is https://github.com/totvs/TDS-WebToolKit.git, branch: DEV.

I appreciate the support.

**Comment by brodao2** [comment]
Resolved. Thank you very much.
